### ISSUE TITLE
7.0.0 Roadmap

### ISSUE THREAD

**Issue by ctavan** [uuidjs/uuid#343]
Umbrella issue to give an overview of what's planned for v7.0.0:

- [x] ESM Build for the browser: #330, #245
- [x] Drop default export: #370
- [x] Platform Support matrix & Browser tests: #340
- [x] Automated Release / Changelog generation -> Was already mostly there. Full automation is maybe not a goal given that this library doesn't change so often at the moment.
- [x] Monitor bundlesize? #353
- [x] Improved TypeScript definitions (node Node.js dep for Browser): #328 DefinitelyTyped/DefinitelyTyped#41814
- [x] Insecure RNG Opt-In: #173, #354, #294
- [x] Rename package script to build
- [x] Add umd build to package: #345, #364, #302
- [x] Update docs to use import: #363

Out of scope:
- ESM Build for Node.js: #342

**Comment by ctavan** [comment]
We have just released [`uuid@7.0.0`](https://github.com/uuidjs/uuid/blob/v7.0.0/CHANGELOG.md#700-2020-02-24) which contains all issues from this umbrella issue.

Please feel free to open a new issue if you encounter any issues with the new version.
