### ISSUE TITLE
Tracking Issue: RFC 9562 / uuid@10

### ISSUE THREAD

**Issue by broofa** [uuidjs/uuid#749]
### RFC9562-related tasks

* [x] Review and merge #681 (also #751)
* [x] Review and merge #714
* [x] Add v6 support (#754)
* [x] Add v8 support (#758, #759)
* [x] Test `validate()` passes with new versions (6-8) (#759)
* [x] Test `version()` works with new versions (6-8) (#759)
* [x] Update all references to RFC 4122 -> RFC 9562 (#753)

### Other tasks
* [x] Drop support for node < 16.  (node LTS is currently node@180 (#750) 
* [x] #736

**Comment by broofa** [comment]
`uuid@10` has been published
